### ISSUE TITLE
[Tópicos/01] - Show de bola mestre!

### ISSUE THREAD

**Issue by lucasferreira** [marcjcs/SATC#1]
Fala mestre Marcos,

Cara eu gostei bastante do teu exercício já havia dado uma olhada em sala de aula e achei bem legal tua ideia de carrinho de compras, serviu perfeitamente para o propósito de trabalhar com hooks e etc.

Está muito bem dividido e "componentizado", gostei bastante da forma como tu deixou tudo que é "modificador" no App e os componentes secundário apenas executam o que recebem (deixando assim tudo desacoplado).

Também gostei do fato de usares Tailwind CSS é um baita framework utilitário.

Se me permitires uma sugestão, talvez tu até já saibas disso, não que este simples exercício precise de qualquer otimização de performance mas eu percebi que a "api" dos callbacks quase sempre bate com a função executora, tipo aqui:

https://github.com/marcjcs/SATC/blob/68c89a776d2a4330a23bf6406bf6c3b305f4f075/T%C3%B3picos%20Especiais/01/src/App.jsx#L55

No caso acima (e em outros semelhantes) seria mais performático deixar apenas assim:

`<ShopList items={items} addToCart={onAddItem} /> `

A função `onAddItem` recebe exatamente o mesmo argumento enviado via `addToCart`, logo se passarmos uma referencia direta para função economizamos na criação de menos funções "on-the-fly" a cada vez que uma re-renderização do React acontece em tela.

Claro essa é uma otimização prematura, não há necessidade de fazer isso enquanto tu não sentir a interface _"lagada"_ porém estou sugerindo só para ter certeza que tu já sabes deste conceito e possa utiliza-lo em futuros projetos mais complexos.

Tmj 👊

**Comment by yakusho** [comment]
Opa, e aí prof.,

Então, fiz um pouco na correria então não tinha prestado muita atenção nisso, na verdade não sabia que isso poderia melhorar a performance, mas acho mais "bonito" só passar a função, eu acabo meio que por reflexo evitando fazer isso porque já tive alguns problemas no passado onde só passar a função não rolava, aí eu tinha que colocar `() => func()` se não o código não rodava.

Valeu pelo feedback :fist_oncoming:
E surpreso que acabou achando a atividade, acho que essa tarefa em especifico eu mandei o link do repo antigo :grin:
